version: "3.9"

services:
  app:
    image: mariadb-springboot:latest
    container_name: mariadb-springboot
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./:/app
    command: ["mvn", "exec:java", "spring-boot:run"]
  database:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jpa_jdbc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
